[package]
name = "Filed"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["clock"] }
iced = { version = "0.13.1", features = ["lazy", "tokio", "wgpu"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.7.0"
